-- MySQL Script generated by MySQL Workbench
-- 01/20/18 20:14:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema siakad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema siakad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siakad` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `siakad` ;

-- -----------------------------------------------------
-- Table `siakad`.`dosen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siakad`.`dosen` (
  `id` INT(11) NOT NULL COMMENT '',
  `nip` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `nama` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `alamat` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `no_tlp` INT(11) NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `nip_UNIQUE` (`nip` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siakad`.`absen_dosen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siakad`.`absen_dosen` (
  `id` INT(11) NOT NULL COMMENT '',
  `dosen_id` INT(11) NOT NULL COMMENT '',
  `absen` ENUM('1','2','3') NULL DEFAULT NULL COMMENT '',
  `ket` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `absen_at` TIME NULL COMMENT '',
  `absen_date` DATE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_absen_dosen_dosen1_idx` (`dosen_id` ASC)  COMMENT '',
  CONSTRAINT `fk_absen_dosen_dosen1`
    FOREIGN KEY (`dosen_id`)
    REFERENCES `siakad`.`dosen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siakad`.`jenjang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siakad`.`jenjang` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `jenjang` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siakad`.`progstu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siakad`.`progstu` (
  `id` INT(11) NOT NULL COMMENT '',
  `nama` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `jenjang_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_progstu_jenjang1_idx` (`jenjang_id` ASC)  COMMENT '',
  CONSTRAINT `fk_progstu_jenjang1`
    FOREIGN KEY (`jenjang_id`)
    REFERENCES `siakad`.`jenjang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siakad`.`mahasiswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siakad`.`mahasiswa` (
  `id` INT(11) NOT NULL COMMENT '',
  `nim` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `nama` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `jk` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `alamat` TINYTEXT NULL DEFAULT NULL COMMENT '',
  `progstu_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `nim_UNIQUE` (`nim` ASC)  COMMENT '',
  INDEX `fk_mahasiswa_jurusan1_idx` (`progstu_id` ASC)  COMMENT '',
  CONSTRAINT `fk_mahasiswa_jurusan1`
    FOREIGN KEY (`progstu_id`)
    REFERENCES `siakad`.`progstu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siakad`.`matkul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siakad`.`matkul` (
  `id` INT(11) NOT NULL COMMENT '',
  `kd_matkul` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `progstu_id` INT(11) NOT NULL COMMENT '',
  `nama` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `semester` INT(2) NULL DEFAULT NULL COMMENT '',
  `sks` INT(2) NULL DEFAULT NULL COMMENT '',
  `kategori` VARCHAR(15) NULL DEFAULT NULL COMMENT '',
  `dosen_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `kd_matkul_UNIQUE` (`kd_matkul` ASC)  COMMENT '',
  INDEX `fk_matkul_jurusan1_idx` (`progstu_id` ASC)  COMMENT '',
  INDEX `fk_matkul_dosen1_idx` (`dosen_id` ASC)  COMMENT '',
  CONSTRAINT `fk_matkul_jurusan1`
    FOREIGN KEY (`progstu_id`)
    REFERENCES `siakad`.`progstu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matkul_dosen1`
    FOREIGN KEY (`dosen_id`)
    REFERENCES `siakad`.`dosen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siakad`.`absen_mhs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siakad`.`absen_mhs` (
  `id` INT(11) NOT NULL COMMENT '',
  `mahasiswa_id` INT(11) NOT NULL COMMENT '',
  `absen` ENUM('1','2','3') NULL DEFAULT NULL COMMENT '',
  `ket` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `matkul_id` INT(11) NOT NULL COMMENT '',
  `absen_at` TIME NULL COMMENT '',
  `absen_date` DATE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_absen_mhs_mahasiswa1_idx` (`mahasiswa_id` ASC)  COMMENT '',
  INDEX `fk_absen_mhs_matkul1_idx` (`matkul_id` ASC)  COMMENT '',
  CONSTRAINT `fk_absen_mhs_mahasiswa1`
    FOREIGN KEY (`mahasiswa_id`)
    REFERENCES `siakad`.`mahasiswa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_absen_mhs_matkul1`
    FOREIGN KEY (`matkul_id`)
    REFERENCES `siakad`.`matkul` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siakad`.`berita_acara_kuliah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siakad`.`berita_acara_kuliah` (
  `id` INT(11) NOT NULL COMMENT '',
  `progstu_id` INT(11) NOT NULL COMMENT '',
  `dosen_id` INT(11) NOT NULL COMMENT '',
  `tanngal` DATE NULL DEFAULT NULL COMMENT '',
  `masuk` DATETIME NULL DEFAULT NULL COMMENT '',
  `selesai` DATETIME NULL DEFAULT NULL COMMENT '',
  `materi` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `jumlah_mhs` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_berita_acara_kuliah_progstu1_idx` (`progstu_id` ASC)  COMMENT '',
  INDEX `fk_berita_acara_kuliah_dosen1_idx` (`dosen_id` ASC)  COMMENT '',
  CONSTRAINT `fk_berita_acara_kuliah_dosen1`
    FOREIGN KEY (`dosen_id`)
    REFERENCES `siakad`.`dosen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_berita_acara_kuliah_progstu1`
    FOREIGN KEY (`progstu_id`)
    REFERENCES `siakad`.`progstu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siakad`.`tahun_ajaran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siakad`.`tahun_ajaran` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tahun_ajaran` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siakad`.`semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siakad`.`semester` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `semester` INT(2) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siakad`.`mahasiswa_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siakad`.`mahasiswa_detail` (
  `id` INT(11) NOT NULL COMMENT '',
  `mahasiswa_id` INT(11) NOT NULL COMMENT '',
  `nilai` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `tahun_ajaran_id` INT NOT NULL COMMENT '',
  `semester_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_mahasiswa_detail_mahasiswa1_idx` (`mahasiswa_id` ASC)  COMMENT '',
  INDEX `fk_mahasiswa_detail_tahun_ajaran1_idx` (`tahun_ajaran_id` ASC)  COMMENT '',
  INDEX `fk_mahasiswa_detail_semester1_idx` (`semester_id` ASC)  COMMENT '',
  CONSTRAINT `fk_mahasiswa_detail_mahasiswa1`
    FOREIGN KEY (`mahasiswa_id`)
    REFERENCES `siakad`.`mahasiswa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mahasiswa_detail_tahun_ajaran1`
    FOREIGN KEY (`tahun_ajaran_id`)
    REFERENCES `siakad`.`tahun_ajaran` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mahasiswa_detail_semester1`
    FOREIGN KEY (`semester_id`)
    REFERENCES `siakad`.`semester` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siakad`.`ruangan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siakad`.`ruangan` (
  `id` INT(11) NOT NULL COMMENT '',
  `kd_ruangan` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `dosen_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `kd_ruangan_UNIQUE` (`kd_ruangan` ASC)  COMMENT '',
  INDEX `fk_ruangan_dosen1_idx` (`dosen_id` ASC)  COMMENT '',
  CONSTRAINT `fk_ruangan_dosen1`
    FOREIGN KEY (`dosen_id`)
    REFERENCES `siakad`.`dosen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siakad`.`paket_head`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siakad`.`paket_head` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nama_paket` VARCHAR(10) NULL COMMENT '',
  `progstu_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_paket_head_progstu1_idx` (`progstu_id` ASC)  COMMENT '',
  CONSTRAINT `fk_paket_head_progstu1`
    FOREIGN KEY (`progstu_id`)
    REFERENCES `siakad`.`progstu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siakad`.`paket_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siakad`.`paket_detail` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `sks` VARCHAR(5) NOT NULL COMMENT '',
  `paket_head_id` INT NOT NULL COMMENT '',
  `kd_matkul` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_paket_detail_paket_head1_idx` (`paket_head_id` ASC)  COMMENT '',
  INDEX `fk_paket_detail_matkul1_idx` (`kd_matkul` ASC)  COMMENT '',
  CONSTRAINT `fk_paket_detail_paket_head1`
    FOREIGN KEY (`paket_head_id`)
    REFERENCES `siakad`.`paket_head` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paket_detail_matkul1`
    FOREIGN KEY (`kd_matkul`)
    REFERENCES `siakad`.`matkul` (`kd_matkul`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
